name = "EmissionExpressions"
uuid = "6828d65a-07f4-472f-b28b-41bf2a163c8d"
authors = ["Maeve Andersen <maeve.andersen@colorado.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
