name: TagBot
on:
  issue_comment:
    types:
      - created
  workflow_dispatch:
jobs:
  TagBot:
    if: github.event_name == 'workflow_dispatch' || github.actor == 'JuliaTagBot'
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.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 }}
          ssh: ${{ secrets.DOCUMENTER_KEY }}
